/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.jackos2500.droidtop.initservice;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Reason implements org.apache.thrift.TEnum {
  SERVICE_MANAGER_NOT_RUNNING(0),
  ERROR(1);

  private final int value;

  private Reason(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Reason findByValue(int value) { 
    switch (value) {
      case 0:
        return SERVICE_MANAGER_NOT_RUNNING;
      case 1:
        return ERROR;
      default:
        return null;
    }
  }
}
